export const TABS_OPEN_CREATE_PROJECT = 'TABS/OPEN_CREATE_PROJECT';
export const TABS_OPEN_PROJECT = 'TABS/OPEN_PROJECT';
export const TABS_ACTIVATE = 'TABS/ACTIVATE';
export const TABS_SET_EDIT_MODE = 'TABS/SET_EDIT_MODE';
export const TABS_CLOSE = 'TABS/CLOSE';

export const MENU_SET_ACTIVE_ITEM = 'MENU/SET_ACTIVE_ITEM';

export const PROJECT_PROJECTS_LOADED = 'PROJECT/PROJECTS_LOADED';
export const PROJECT_NEW = 'PROJECT/NEW';
export const PROJECT_EDIT = 'PROJECT/EDIT';
export const PROJECT_DELETE = 'PROJECT/DELETE';